### ISSUE TITLE
Would You Like a GitHub Actions Workflow For Publishing the Site to GitHub Pages?

### ISSUE THREAD

**Issue by zicklag** [myriadrf/LimeSDR-Mini-v2#1]
Hey there! Just found this project, an was curious whether or not you wanted me to setup a quick GitHub actions workflow to build and publish the docs site to GitHub pages.

**Comment by 9600** [comment]
Thanks for the offer, but will be setting this up to publish to Netlify, alongside other docs that we're in the process of migrating to Sphinx. Should be completed later this week.
