### ISSUE TITLE
Solid green light and no USB Enumeration

### ISSUE THREAD

**Issue by scj643** [myriadrf/LimeSDR-Mini-v2#6]
I was using my LimeSDR Mini yesterday and it was working fine and this morning I went to use it and now it's not enumerating and has a solid green LED. It does not even show up in dmesg when plugged in. I have tried multiple USB ports with no luck.

**Comment by 9600** [comment]
Hello,

Support is provided via the MyriadRF forums and if you could please post there, then someone could take a look. This issue tracker is just for hardware design related issues.

https://discourse.myriadrf.org/
